import type { NextPage } from 'next';
import Head from 'next/head';
import useTranslation from 'next-translate/useTranslation';

const Home: NextPage = () => {
  const { t } = useTranslation('home');
  return (
    <div>
      <Head>
        <title>Airweb | {t`E-shop`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header className="h-10 border-2  border-cyan-500">Header</header>

      <main className="border-2 border-cyan-500 min-h-[calc(100vh-80px)]">
        <h1>{t`Hello evryone`}</h1>
      </main>

      <footer className="h-10 border-2 border-cyan-500">
        <p>Footer</p>
      </footer>
    </div>
  );
};

export default Home;
