import { NextPageContext } from 'next';
import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head';
import useSWR from 'swr';

import { StaleIndicator } from '@/components/loading';
import { ssrRedirect, routeNames, createSSRHttpClient, endPoints } from '@/support';
import { Category, Product } from '@/types';

// eslint-disable-next-line react/function-component-definition
export default function Index({
  ssrCategories,
  ssrProducts,
}: {
  ssrProducts: Product[];
  ssrCategories: Category[];
}) {
  const { t } = useTranslation('home');
  const { data: products, isValidating } = useSWR<Product[]>(endPoints.products, {
    fallbackData: ssrProducts,
  });

  const { data: categories } = useSWR<Category[]>(endPoints.categories, {
    fallbackData: ssrCategories,
  });
  const productsByCategory = categories?.map((category) => {
    const productfiltred = products?.filter((product) => product.category_id === category.id);

    return { ...category, productfiltred };
  });

  return (
    <div>
      <Head>
        <title>Airweb | {t`E-shop`}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.png" rel="icon" />
      </Head>
      <StaleIndicator isValidating={isValidating}>
        {productsByCategory?.map((c) => (
          <section key={c.id} className="col">
            <h2 className="font-bold">{c.label}</h2>
            {c.productfiltred?.map((p) => (
              <h2 key={p.id}> {p.label} </h2>
            ))}
          </section>
        ))}
      </StaleIndicator>
    </div>
  );
}

export const getServerSideProps = async ({ req }: NextPageContext) => {
  try {
    const httpClient = createSSRHttpClient(req);
    const ssrProducts = await httpClient.get<Product[]>(endPoints.products);
    const ssrCategories = await httpClient.get<Category[]>(endPoints.categories);

    return {
      props: { ssrProducts, ssrCategories },
    };
  } catch (error) {
    return ssrRedirect(routeNames.error);
  }
};
